
services:
  mt5-bridge:
    ipc: host
    security_opt:
      - label:disable
    volumes:
      - type: volume
        source: mt5-data
        target: /data
      - ./data:/data/seed:ro,Z

volumes:
  mt5-data:
